-- Adds the educational-organizations outreach template, converted from a real email Joel sent to
-- ISACS (an independent-school association) for their Nov 5-6 annual conference. Targeted via the
-- new outreach_templates.industry_segment_id (see sales-platform-add-industry-segment-override.sql
-- and lib/sales/db/outreach.ts#findApprovedTemplate) rather than opportunity_type_id, since the fit
-- here is about the *organization's sector*, not the opportunity type.
--
-- Differences from 'General purpose — v1 default' (see sales-platform-update-template-voice.sql),
-- both deliberate, not oversights:
--   1. The "We've found that educational conferences..." paragraph is fixed literal text (generic
--      to every education-sector org), not {{fit_reason}} — {{fit_reason}} is still generated by
--      the shared structured-output call in draft.ts, it's simply unused by this template's body.
--   2. Sign-off is bare "Best,\nJoel" — no {{sender_name}} placeholder, and no signature block /
--      press-quote footer after it — for a shorter, more personal tone than the general template.
--
-- Run this AFTER sales-platform-add-industry-segment-override.sql (needs its
-- outreach_templates.industry_segment_id column and the 'education' industry_segments row, which
-- already exists from sales-platform-tables.sql). Run once in the Supabase SQL Editor.

insert into public.outreach_templates (name, opportunity_type_id, industry_segment_id, body_template, status)
select
  'Educational — v1 default',
  null,
  (select id from public.industry_segments where key = 'education'),
  E'Hi {{contact_first_name}},\n\nI hope you''re doing well!\n\nI''m {{sender_name}}, founder of Crowdsource Choir — a participatory musical experience where the audience becomes the choir. {{opening_reason}}\n\nWe''ve found that educational conferences are a particularly natural fit for Crowdsource Choir. Educators tend to arrive curious, collaborative, and willing to participate, so they quickly move from being an audience to becoming creators. By the end of the experience, they''ve not only learned together—they''ve created something together that''s unique to that gathering.\n\nI''ve included a bit more about the experience here:\n{{book_url}}\n\n{{cta}}\n\nThanks, and I hope we have a chance to connect.\n\nBest,\nJoel',
  'approved'
where not exists (
  select 1 from public.outreach_templates where name = 'Educational — v1 default'
);
