-- Ballard FC Song Garden demo seed (idempotent upsert by slug)
insert into public.gardens (
  slug, title, kind, status, brand_kit, world_state, world_version, mutation_policy, commerce
) values (
  'ballard-fc',
  'Ballard FC Song Garden',
  'season',
  'live',
  '{"title":"Ballard FC","logoUrl":"/fans/ballard-fc/logo.png","primaryColor":"#0B1F3A","accentColor":"#CFFF81","heroArtworkUrl":"/fans/ballard-fc/interbay-stadium-map.jpg","animationPreset":"particles","ambientSoundtrackUrl":null,"bloomStoryboard":[],"zones":[{"key":"supporters","label":"Supporters","sponsorKey":null,"x":0.78,"y":0.24,"blurb":"Loudest end — leave a mark with the ultras.","prompt":"What''s your chant idea for the next game?","ctaLabel":"Share your chant","inputPlaceholder":"Type a chant line…"},{"key":"beer-garden","label":"Beer Garden","sponsorKey":"stoup","x":0.9,"y":0.38,"blurb":"Service Station #1 — Stoup sideline energy.","prompt":"What song should blast at the Stoup stand?","ctaLabel":"Leave a mark","inputPlaceholder":"Song, vibe, or shout…"},{"key":"tequila-zone","label":"Tequila Zone","sponsorKey":"orgullo-ajeno","x":0.86,"y":0.58,"blurb":"21+ corner — Orgullo Ajeno.","prompt":"Drop a toast for the 21+ corner.","ctaLabel":"Leave a mark","inputPlaceholder":"Your toast…"},{"key":"standing-room","label":"Standing Room","sponsorKey":null,"x":0.32,"y":0.3,"blurb":"On your feet along the north stand.","prompt":"Who are you standing with tonight?","ctaLabel":"Check in","inputPlaceholder":"Crew, friends, solo…"},{"key":"family","label":"Family Section","sponsorKey":null,"x":0.44,"y":0.3,"blurb":"Alcohol-free GA — bring the kids.","prompt":"What''s your family''s matchday ritual?","ctaLabel":"Leave a mark","inputPlaceholder":"A small ritual…"},{"key":"merch-tent","label":"Merch Tent","sponsorKey":null,"x":0.2,"y":0.26,"blurb":"Kits, scarves, and matchday gear.","prompt":"What kit piece should Ballard drop next?","ctaLabel":"Leave a mark","inputPlaceholder":"Scarf, kit, colorway…"},{"key":"pagliacci-pitch","label":"Pagliacci Pitch","sponsorKey":"pagliacci","x":0.5,"y":0.56,"blurb":"Center circle — the shared Song Garden heart.","prompt":"What''s your chant idea for the next game?","ctaLabel":"Share your chant","inputPlaceholder":"Type a chant line…"},{"key":"south-new","label":"South Stand","sponsorKey":null,"x":0.52,"y":0.9,"blurb":"New / coming seating — claim the south roar.","prompt":"Claim the south roar — what should it sound like?","ctaLabel":"Leave a mark","inputPlaceholder":"A roar, a phrase…"},{"key":"bike-parking","label":"Bike Parking","sponsorKey":"wombi","x":0.12,"y":0.16,"blurb":"Roll up with Wombi.","prompt":"How did you roll into Interbay?","ctaLabel":"Check in","inputPlaceholder":"Bike, bus, walk…"}],"sponsors":[{"key":"pagliacci","name":"Pagliacci Pizza","logoUrl":null,"credit":"Pagliacci Pitch"},{"key":"stoup","name":"Stoup Brewing","logoUrl":null,"credit":"Enabled by Stoup Brewing"},{"key":"orgullo-ajeno","name":"Orgullo Ajeno","logoUrl":null,"credit":"Orgullo Ajeno Tequila"},{"key":"bridges-united","name":"Bridges United Foundation","logoUrl":null,"credit":"Bridges United Foundation"},{"key":"wombi","name":"Wombi","logoUrl":null,"credit":"Wombi Bike Parking"}]}'::jsonb,
  '{"version":0,"updatedAt":"2026-08-10T23:33:00.524Z","energy":0,"totals":{"contributions":0,"participants":0,"byKind":{}},"field":{"nodes":[],"nextIndex":0},"landmarks":[],"layers":{"text":0,"voice":0,"video":0,"percussion":0,"vocal":0,"other":0},"chapters":{"completedIds":[],"activeChapterId":null},"zones":{},"renderSeed":"garden_ballard"}'::jsonb,
  0,
  '{"energyPerContribution":0.012,"energyCap":1,"layerGain":0.02,"layerCap":1,"chapterWeightDefault":1,"betweenChapterWeight":0.5,"chapterFinaleWeight":1.5,"landmarks":[{"key":"north_grove","label":"North Grove","minEnergy":0.2},{"key":"choir_clearing","label":"Choir Clearing","minEnergy":0.45},{"key":"full_bloom","label":"Full Bloom","minEnergy":0.75}],"maxNodes":240,"nodeWeight":1,"deviceDamping":{"windowMinutes":30,"afterCount":5,"factor":0.35}}'::jsonb,
  null
)
on conflict (slug) do update set
  title = excluded.title,
  kind = excluded.kind,
  status = excluded.status,
  brand_kit = excluded.brand_kit,
  mutation_policy = excluded.mutation_policy,
  updated_at = now();
