import type { SeedOrgWithContactsInput } from "@/lib/sales/seed/seed-org-with-contacts";

/**
 * Elevate / Vibe / Create / Human-potential / collaboration conference shortlist (29).
 * Contacts prioritized for people directing the conference event (events, programming,
 * producers, curators, EDs). Hunter Domain Search + Email Finder + Verifier (2026-10-10).
 */
export const ELEVATE_VIBE_CREATE_PROSPECTS: SeedOrgWithContactsInput[] = [
  {
    name: "Elevate — Swaim Strategies",
    websiteUrl: "https://swaimstrategies.com/elevate-conference/",
    locationCity: "Portland",
    locationRegion: "OR",
    locationCountry: "US",
    organizationTypeKey: "conference",
    salesInitiative: "conferences_associations",
    opportunityTypeKey: "annual_conference",
    forceManualQueue: true,
    runPipeline: false,
    manualEventName: "Elevate 2027",
    manualQueueTitle: "Elevate 2027 (Swaim) — Portland (Mar 2–3) participatory anthem",
    manualQueueDescription:
      "Swaim Strategies nonprofit fundraising-events conference. Pitch a shared-creation anthem for fundraiser planners.",
    eventDateEstimate: "2027-03-02",
    eventDateConfidence: "confirmed",
    contacts: [
      {
        fullName: "Mary Elizabeth",
        email: "mary@swaimstrategies.com",
        roleTitle: "Conference Coordinator",
        roleCategory: "events",
        emailVerificationStatus: "verified_deliverable",
        roleDescription: "Published Elevate contact — owns attendee and speaker logistics for the hybrid Portland conference.",
      },
      {
        fullName: "Samantha Swaim",
        email: "sam@swaimstrategies.com",
        roleTitle: "Founder / Fundraising Consultant",
        roleCategory: "executive",
        emailVerificationStatus: "verified_deliverable",
        roleDescription: "Firm founder — green-lights conference programming and experience design.",
      },
      {
        fullName: "Kristin Steele",
        email: "kristin@swaimstrategies.com",
        roleTitle: "Creative Director",
        roleCategory: "marketing",
        emailVerificationStatus: "verified_deliverable",
        roleDescription: "Creative director — owns how the live experience looks and feels for attendees.",
      },
    ],
  },
  {
    name: "Elevate Community & Conference",
    websiteUrl: "https://elevatecommunity.net/",
    locationCity: "San Diego",
    locationRegion: "CA",
    locationCountry: "US",
    organizationTypeKey: "conference",
    salesInitiative: "conferences_associations",
    opportunityTypeKey: "annual_conference",
    forceManualQueue: true,
    runPipeline: false,
    manualEventName: "Elevate Community & Conference 2027",
    manualQueueTitle: "Elevate Community 2027 — San Diego (Jun 14–16) participatory anthem",
    manualQueueDescription:
      "Independent-school marketing community conference. Pitch a belonging anthem for school marcom leaders.",
    eventDateEstimate: "2027-06-14",
    eventDateConfidence: "confirmed",
    contacts: [
      {
        fullName: "Phil Goodman",
        email: "phil@elevatecommunity.net",
        roleTitle: "Executive Director / Founder",
        roleCategory: "executive",
        emailVerificationStatus: "verified_deliverable",
        roleDescription: "Founder and ED — directs Elevate programming and host-school partnerships.",
      },
      {
        fullName: "Libby Alvarez",
        email: "libby@elevatecommunity.net",
        roleTitle: "Associate Director",
        roleCategory: "events",
        emailVerificationStatus: "verified_deliverable",
        roleDescription: "Associate director — sponsorship and conference operations doorway.",
      },
      {
        fullName: "Dawn Saunders",
        email: "dsaunders@sfcs.net",
        roleTitle: "Advisory Council / Marketing Director (Santa Fe Christian)",
        roleCategory: "events",
        emailVerificationStatus: "verified_deliverable",
        roleDescription: "Elevate Advisory Council member and school marketing director — helps steward conference direction.",
      },
    ],
  },
  {
    name: "ELEVATE — Mark43",
    websiteUrl: "https://elevate.mark43.com/2027",
    locationCity: "New Orleans",
    locationRegion: "LA",
    locationCountry: "US",
    organizationTypeKey: "corporation",
    salesInitiative: "tech_conferences",
    opportunityTypeKey: "annual_conference",
    forceManualQueue: true,
    runPipeline: false,
    manualEventName: "ELEVATE 2027 (Mark43)",
    manualQueueTitle: "ELEVATE 2027 (Mark43) — New Orleans (Mar 7–9) participatory anthem",
    manualQueueDescription:
      "Mark43 public-safety software customer conference. Pitch a participatory anthem for the user community.",
    eventDateEstimate: "2027-03-07",
    eventDateConfidence: "confirmed",
    contacts: [
      {
        fullName: "Jackie Nese",
        email: "jackie.nese@mark43.com",
        roleTitle: "Senior Events Manager",
        roleCategory: "events",
        emailVerificationStatus: "verified_deliverable",
        roleDescription: "Senior events manager — primary owner of ELEVATE conference production.",
      },
      {
        fullName: "Matthew Polega",
        email: "matthew@mark43.com",
        roleTitle: "Managing Director",
        roleCategory: "executive",
        emailVerificationStatus: "verified_deliverable",
        roleDescription: "Managing director — can green-light flagship customer-event programming.",
      },
      {
        fullName: "Bob Hughes",
        email: "bob.hughes@mark43.com",
        roleTitle: "Chief Executive Officer",
        roleCategory: "executive",
        emailVerificationStatus: "verified_deliverable",
        roleDescription: "CEO — owns the customer-conference vision and keynote-scale moments.",
      },
    ],
  },
  {
    name: "Elevate — UK",
    websiteUrl: "https://www.elevatearena.com/",
    locationCity: null,
    locationRegion: null,
    locationCountry: "GB",
    organizationTypeKey: "conference",
    salesInitiative: "tech_conferences",
    opportunityTypeKey: "annual_conference",
    forceManualQueue: true,
    runPipeline: false,
    manualEventName: "Elevate UK 2027",
    manualQueueTitle: "Elevate UK 2027 — participatory anthem (6,500+ historical)",
    manualQueueDescription:
      "Large UK technology/arena conference (Elevate). Pitch a hall-scale participatory anthem.",
    eventDateEstimate: null,
    eventDateConfidence: "unknown",
    contacts: [
      {
        fullName: "Lucy Findlay",
        email: "lucy.findlay@elevatearena.com",
        roleTitle: "Event Director",
        roleCategory: "events",
        emailVerificationStatus: "verified_deliverable",
        roleDescription: "Event director — primary buyer for on-site programming and live experiences.",
      },
      {
        fullName: "Lukas Wojcik",
        email: "lukas.wojcik@elevatearena.com",
        roleTitle: "Marketing Manager",
        roleCategory: "marketing",
        emailVerificationStatus: "verified_deliverable",
        roleDescription: "Marketing manager — owns how a live moment extends into conference story.",
      },
      {
        fullName: "Denise Fairbrother",
        email: "denise.fairbrother@elevatearena.com",
        roleTitle: "Business Development Manager",
        roleCategory: "marketing",
        emailVerificationStatus: "verified_deliverable",
        roleDescription: "Business development — sponsorship and partner programming doorway.",
      },
    ],
  },
  {
    name: "ELEVATE Cyber & AI Summit",
    websiteUrl: "https://elevateaisummit.com/",
    locationCity: "Dubai",
    locationRegion: null,
    locationCountry: "AE",
    organizationTypeKey: "conference",
    salesInitiative: "tech_conferences",
    opportunityTypeKey: "annual_conference",
    forceManualQueue: true,
    runPipeline: false,
    manualEventName: "ELEVATE Cyber & AI Summit 2027",
    manualQueueTitle: "ELEVATE Cyber & AI Summit — Dubai (Feb 2) participatory anthem",
    manualQueueDescription:
      "Dubai AI/cyber summit (Odyssey Concepts UAE). Pitch a participatory close for strategy leaders.",
    eventDateEstimate: "2027-02-02",
    eventDateConfidence: "confirmed",
    contacts: [
      {
        fullName: "Nihad Odyssey",
        email: "nihad@odysseyconceptsuae.com",
        roleTitle: "Conference Organizer (Odyssey Concepts)",
        roleCategory: "events",
        emailVerificationStatus: "verified_deliverable",
        roleDescription: "Odyssey Concepts UAE organizer inbox contact for Elevate AI Summit production.",
      },
      {
        fullName: "Tanees Odyssey",
        email: "tanees@odysseyconceptsuae.com",
        roleTitle: "Conference Organizer (Odyssey Concepts)",
        roleCategory: "events",
        emailVerificationStatus: "verified_deliverable",
        roleDescription: "Odyssey Concepts UAE organizer contact — route programming and speaker asks here.",
      },
      {
        fullName: "Elevate AI Summit",
        email: "info@odysseyconceptsuae.com",
        roleTitle: "Summit information inbox",
        roleCategory: "events",
        emailVerificationStatus: "verified_deliverable",
        roleDescription: "Published organizer inbox for Elevate AI Summit inquiries.",
      },
    ],
  },
  {
    name: "ELEVATE / Freedom Bell",
    websiteUrl: "https://www.elevate-summit.org/events/freedom-bell-vegas-2027",
    locationCity: "Las Vegas",
    locationRegion: "NV",
    locationCountry: "US",
    organizationTypeKey: "conference",
    salesInitiative: "conferences_associations",
    opportunityTypeKey: "annual_conference",
    forceManualQueue: true,
    runPipeline: false,
    manualEventName: "Freedom Bell Vegas 2027",
    manualQueueTitle: "Freedom Bell 2027 — Las Vegas (Jan 6–10) participatory anthem",
    manualQueueDescription:
      "ELEVATE × EVOKE CES-week gathering. Pitch a participatory anthem for founders/investors room.",
    eventDateEstimate: "2027-01-06",
    eventDateConfidence: "confirmed",
    contacts: [
      {
        fullName: "Craig Shah",
        email: "craigshah@gmail.com",
        roleTitle: "Conference Host (ELEVATE)",
        roleCategory: "executive",
        emailVerificationStatus: "verified_deliverable",
        roleDescription: "Published Freedom Bell / ELEVATE co-host — directs the Vegas convening.",
      },
      {
        fullName: "EVOKE Media",
        email: "info@evokemedia.io",
        roleTitle: "ELEVATE Summit organizer inbox",
        roleCategory: "events",
        emailVerificationStatus: "verified_deliverable",
        roleDescription: "Published ELEVATE Summit / Freedom Bell sponsorship and inquiry inbox.",
      },
      {
        fullName: "EVOKE Admissions",
        email: "admissions@evokemedia.io",
        roleTitle: "Freedom Bell / EVOKE admissions",
        roleCategory: "events",
        emailVerificationStatus: "verified_deliverable",
        roleDescription: "EVOKE admissions inbox — doorway for attendee and host-side Freedom Bell asks (Jen Du Plessis co-hosts; no public work email).",
      },
    ],
  },
  {
    name: "VIBE Conference — Questex",
    websiteUrl: "https://www.vibeconference.com/",
    locationCity: "Dallas",
    locationRegion: "TX",
    locationCountry: "US",
    organizationTypeKey: "conference",
    salesInitiative: "conferences_associations",
    opportunityTypeKey: "annual_conference",
    forceManualQueue: true,
    runPipeline: false,
    manualEventName: "VIBE Conference 2027",
    manualQueueTitle: "VIBE Conference 2027 — Dallas (Feb 22–24) participatory anthem",
    manualQueueDescription:
      "Questex on-premise beverage executive conference. Pitch a participatory anthem for multi-unit operators.",
    eventDateEstimate: "2027-02-22",
    eventDateConfidence: "confirmed",
    contacts: [
      {
        fullName: "Zohaib Sheikh",
        email: "zsheikh@questex.com",
        roleTitle: "Director of Conference Programming",
        roleCategory: "events",
        emailVerificationStatus: "verified_deliverable",
        roleDescription: "Director of conference programming — owns session and stage content for Questex events including VIBE.",
      },
      {
        fullName: "Lucia Contreras",
        email: "lcontreras@questex.com",
        roleTitle: "Director of Conferences",
        roleCategory: "events",
        emailVerificationStatus: "verified_deliverable",
        roleDescription: "Director of conferences — senior owner of Questex conference portfolio operations.",
      },
      {
        fullName: "Brandy Rand",
        email: "brand@questex.com",
        roleTitle: "Vice President & Market Leader (VIBE)",
        roleCategory: "executive",
        emailVerificationStatus: "verified_deliverable",
        roleDescription: "Published VIBE market leader — primary executive contact for the beverage conference.",
      },
    ],
  },
  {
    name: "VIBE Market Research Conference",
    websiteUrl: "https://vibemrc.com/about-us/",
    locationCity: null,
    locationRegion: null,
    locationCountry: "US",
    organizationTypeKey: "nonprofit",
    salesInitiative: "conferences_associations",
    opportunityTypeKey: "annual_conference",
    forceManualQueue: true,
    runPipeline: false,
    manualEventName: "VIBE Black Market Research Conference 2027",
    manualQueueTitle: "VIBE MRC 2027 — participatory anthem (CoBMR)",
    manualQueueDescription:
      "Consortium of Black Market Researchers VIBE insights conference. Pitch a belonging anthem for the research community.",
    eventDateEstimate: "2027-03-17",
    eventDateConfidence: "confirmed",
    contacts: [
      {
        fullName: "Tikica Benjamin",
        email: "tikica@cobmr.org",
        roleTitle: "Founder, VIBE Conference / President, CoBMR",
        roleCategory: "executive",
        emailVerificationStatus: "verified_deliverable",
        roleDescription: "Founder of VIBE and CoBMR president — directs the conference vision and programming.",
      },
      {
        fullName: "CoBMR Events",
        email: "hello@cobmr.org",
        roleTitle: "CoBMR conference inbox",
        roleCategory: "events",
        emailVerificationStatus: "verified_deliverable",
        roleDescription: "Published CoBMR inbox for VIBE speaking, sponsorship, and conference inquiries.",
      },
      {
        fullName: "Lisa Williams",
        email: "lisa@vibemrc.com",
        roleTitle: "VIBE MRC contact",
        roleCategory: "events",
        emailVerificationStatus: "risky",
        roleDescription: "VIBE MRC domain contact — route conference operations asks here if CoBMR inbox is slow.",
      },
    ],
  },
  {
    name: "CREATE — Informa",
    websiteUrl: "https://informaconnect.com/create/",
    locationCity: null,
    locationRegion: null,
    locationCountry: "US",
    organizationTypeKey: "conference",
    salesInitiative: "conferences_associations",
    opportunityTypeKey: "annual_conference",
    forceManualQueue: true,
    runPipeline: false,
    manualEventName: "CREATE (Informa Connect)",
    manualQueueTitle: "CREATE (Informa) — participatory anthem",
    manualQueueDescription:
      "Informa Connect CREATE conference. Pitch a participatory anthem for the CREATE community.",
    eventDateEstimate: null,
    eventDateConfidence: "unknown",
    contacts: [
      {
        fullName: "Chabelyz Mejia",
        email: "chabelyz.mejia@informaconnect.com",
        roleTitle: "Event Operations Manager",
        roleCategory: "events",
        emailVerificationStatus: "verified_deliverable",
        roleDescription: "Event operations manager at Informa Connect — owns on-site conference delivery.",
      },
      {
        fullName: "Harriet Spence",
        email: "harriet.spence@informa.com",
        roleTitle: "Head of Event Operations",
        roleCategory: "events",
        emailVerificationStatus: "verified_deliverable",
        roleDescription: "Head of event operations (Informa) — senior doorway for flagship conference experiences.",
      },
      {
        fullName: "Christopher Lycett",
        email: "christopher.lycett@informa.com",
        roleTitle: "Director of Events",
        roleCategory: "events",
        emailVerificationStatus: "verified_deliverable",
        roleDescription: "Director of events (Informa) — portfolio-level owner for conference programming.",
      },
    ],
  },
  {
    name: "CREATE — She Leads AI",
    websiteUrl: "https://sheleadsai.ai/create-faq/",
    locationCity: "Salt Lake City",
    locationRegion: "UT",
    locationCountry: "US",
    organizationTypeKey: "conference",
    salesInitiative: "tech_conferences",
    opportunityTypeKey: "annual_conference",
    forceManualQueue: true,
    runPipeline: false,
    manualEventName: "CREATE — She Leads AI 2026",
    manualQueueTitle: "CREATE (She Leads AI) — Salt Lake City (Oct 16–18) participatory anthem",
    manualQueueDescription:
      "Human-centered AI conference for women. Pitch a participatory anthem as a conference ritual.",
    eventDateEstimate: "2026-10-16",
    eventDateConfidence: "confirmed",
    contacts: [
      {
        fullName: "Kate Rivera",
        email: "kate@sheleadsai.ai",
        roleTitle: "Conference Experience Lead",
        roleCategory: "events",
        emailVerificationStatus: "verified_deliverable",
        roleDescription: "Conference experience lead — primary owner of how CREATE feels in the room.",
      },
      {
        fullName: "Anne Murphy",
        email: "anne@sheleadsai.ai",
        roleTitle: "Founder & CEO / Conference Host",
        roleCategory: "executive",
        emailVerificationStatus: "verified_deliverable",
        roleDescription: "Founder and CREATE host — green-lights signature programming moments.",
      },
      {
        fullName: "Michelle Muncy-Silva",
        email: "michelle@sheleadsai.ai",
        roleTitle: "Executive Director, She Leads AI Academy",
        roleCategory: "executive",
        emailVerificationStatus: "verified_deliverable",
        roleDescription: "Academy ED on the CREATE hosting team — strong programming collaborator.",
      },
    ],
  },
  {
    name: "Create With Conference",
    websiteUrl: "https://createwith.com/conference",
    locationCity: "Brighton",
    locationRegion: null,
    locationCountry: "GB",
    organizationTypeKey: "conference",
    salesInitiative: "tech_conferences",
    opportunityTypeKey: "annual_conference",
    forceManualQueue: true,
    runPipeline: false,
    manualEventName: "Create With Conference",
    manualQueueTitle: "Create With Conference — Brighton participatory anthem (600+ in 2026)",
    manualQueueDescription:
      "UK AI builders / vibe-coding community conference. Pitch a participatory anthem for builders.",
    eventDateEstimate: null,
    eventDateConfidence: "unknown",
    contacts: [
      {
        fullName: "James Kieran",
        email: "james@createwith.com",
        roleTitle: "Co-organizer / Conference lead",
        roleCategory: "events",
        emailVerificationStatus: "verified_deliverable",
        roleDescription: "Create With conference co-lead — directs the Brighton builder gathering.",
      },
      {
        fullName: "Kieran Ball",
        email: "kieran@createwith.com",
        roleTitle: "Head of Finance & Education / Co-organizer",
        roleCategory: "executive",
        emailVerificationStatus: "verified_deliverable",
        roleDescription: "Named Create With team lead — co-runs conference operations and education track.",
      },
      {
        fullName: "Create With Team",
        email: "team@createwith.com",
        roleTitle: "Conference team inbox",
        roleCategory: "events",
        emailVerificationStatus: "verified_deliverable",
        roleDescription: "Published Create With team inbox for sponsorship and conference inquiries.",
      },
    ],
  },
  {
    name: "CREATE + CO Conference",
    websiteUrl: "https://www.createandco.org/conference",
    locationCity: "Fort Worth",
    locationRegion: "TX",
    locationCountry: "US",
    organizationTypeKey: "nonprofit",
    salesInitiative: "arts_culture",
    opportunityTypeKey: "annual_conference",
    forceManualQueue: true,
    runPipeline: false,
    manualEventName: "CREATE + CO Conference 2026",
    manualQueueTitle: "CREATE + CO — Fort Worth (Jul 24–25) participatory anthem",
    manualQueueDescription:
      "First-gen student leadership conference. Pitch a participatory anthem for students and families.",
    eventDateEstimate: "2026-07-24",
    eventDateConfidence: "confirmed",
    contacts: [
      {
        fullName: "Ricquel Archer",
        email: "ricquel@createandco.org",
        roleTitle: "Founder & CEO",
        roleCategory: "executive",
        emailVerificationStatus: "verified_deliverable",
        roleDescription: "Founder/CEO — owns the annual CREATE + CO conference vision.",
      },
      {
        fullName: "Dominique Cooke",
        email: "dominique@createandco.org",
        roleTitle: "Founding Program Director",
        roleCategory: "events",
        emailVerificationStatus: "verified_deliverable",
        roleDescription: "Program director — owns curriculum and conference session design.",
      },
      {
        fullName: "Laura Soriano",
        email: "laura@createandco.org",
        roleTitle: "Volunteer Engagement Lead",
        roleCategory: "events",
        emailVerificationStatus: "verified_deliverable",
        roleDescription: "Leads volunteer engagement for the conference experience.",
      },
    ],
  },
  {
    name: "CREATE! — Educators",
    websiteUrl: "https://createconference.net/",
    locationCity: "Maumee",
    locationRegion: "OH",
    locationCountry: "US",
    organizationTypeKey: "conference",
    salesInitiative: "conferences_associations",
    opportunityTypeKey: "annual_conference",
    forceManualQueue: true,
    runPipeline: false,
    manualEventName: "CREATE! Educators 2026",
    manualQueueTitle: "CREATE! Educators — Maumee (Jun 4) participatory anthem",
    manualQueueDescription:
      "Educator creativity/technology conference (CATIIE Learning). Pitch a participatory anthem for teachers.",
    eventDateEstimate: "2026-06-04",
    eventDateConfidence: "confirmed",
    contacts: [
      {
        fullName: "Chris Hamady",
        email: "chrishamady@gmail.com",
        roleTitle: "Conference Organizer (CATIIE Learning)",
        roleCategory: "events",
        emailVerificationStatus: "verified_deliverable",
        roleDescription: "Published CREATE! organizer — directs the Maumee educators conference.",
      },
      {
        fullName: "Roger Minier",
        email: "minier@nwoet.org",
        roleTitle: "Executive Director, NWOET",
        roleCategory: "executive",
        emailVerificationStatus: "verified_deliverable",
        roleDescription: "Regional ed-tech ED — partner/programming doorway for CREATE! educator strands.",
      },
      {
        fullName: "Judy Tucker",
        email: "tucker@nwoet.org",
        roleTitle: "Associate Director, NWOET",
        roleCategory: "events",
        emailVerificationStatus: "risky",
        roleDescription: "Associate director at partner org — useful router for educator-conference programming.",
      },
    ],
  },
  {
    name: "CREATE 27 — Grow Stack Drive",
    websiteUrl: "https://growstackdrive.com/create",
    locationCity: "Atlanta",
    locationRegion: "GA",
    locationCountry: "US",
    organizationTypeKey: "conference",
    salesInitiative: "conferences_associations",
    opportunityTypeKey: "annual_conference",
    forceManualQueue: true,
    runPipeline: false,
    manualEventName: "CREATE 27",
    manualQueueTitle: "CREATE 27 — Atlanta (Jan 27–29) participatory anthem",
    manualQueueDescription:
      "Grow Stack Drive faith-based entrepreneur conference. Pitch a participatory anthem for the CREATE community.",
    eventDateEstimate: "2027-01-27",
    eventDateConfidence: "confirmed",
    contacts: [
      {
        fullName: "Ken Joslin",
        email: "ken@growstackdrive.com",
        roleTitle: "Founder & CEO / CREATE Conference",
        roleCategory: "executive",
        emailVerificationStatus: "verified_deliverable",
        roleDescription: "Founder of Grow Stack Drive and CREATE — owns the conference vision.",
      },
      {
        fullName: "Michelle Joslin",
        email: "michelle@growstackdrive.com",
        roleTitle: "Conference hotel & logistics contact",
        roleCategory: "events",
        emailVerificationStatus: "verified_deliverable",
        roleDescription: "Published CREATE hotel/logistics contact — owns attendee operations for the Atlanta conference.",
      },
      {
        fullName: "Susanna Rohm",
        email: "susanna@growstackdrive.com",
        roleTitle: "Grow Stack Drive team",
        roleCategory: "events",
        emailVerificationStatus: "verified_deliverable",
        roleDescription: "GSD team contact on the CREATE conference domain — production collaborator.",
      },
    ],
  },
  {
    name: "Human+Tech Week",
    websiteUrl: "https://www.humantechweek.com/",
    locationCity: "San Francisco",
    locationRegion: "CA",
    locationCountry: "US",
    organizationTypeKey: "conference",
    salesInitiative: "tech_conferences",
    opportunityTypeKey: "annual_conference",
    forceManualQueue: true,
    runPipeline: false,
    manualEventName: "Human+Tech Week 2027",
    manualQueueTitle: "Human+Tech Week 2027 — San Francisco (May 10–14) participatory anthem",
    manualQueueDescription:
      "Human+Tech Week (5,500→10,000). Pitch a hall-scale participatory anthem for the human-centered tech convening.",
    eventDateEstimate: "2027-05-10",
    eventDateConfidence: "confirmed",
    contacts: [
      {
        fullName: "Nichol Bradford",
        email: "nichol@humantechweek.com",
        roleTitle: "Chief Curator",
        roleCategory: "events",
        emailVerificationStatus: "verified_deliverable",
        roleDescription: "Chief curator — owns programming and the experiential arc of Human+Tech Week.",
      },
      {
        fullName: "Rebecca Leung",
        email: "rebecca@humantechweek.com",
        roleTitle: "Media Contact",
        roleCategory: "marketing",
        emailVerificationStatus: "verified_deliverable",
        roleDescription: "Media contact — doorway for story and stage-moment partnerships.",
      },
      {
        fullName: "Meghana Dwaraka",
        email: "meghana@humantechweek.com",
        roleTitle: "Product Manager",
        roleCategory: "operations",
        emailVerificationStatus: "verified_deliverable",
        roleDescription: "Product/ops on the Human+Tech Week team — useful internal router for experience ideas.",
      },
    ],
  },
  {
    name: "ASU+GSV Summit",
    websiteUrl: "https://asugsvsummit.com/",
    locationCity: "San Diego",
    locationRegion: "CA",
    locationCountry: "US",
    organizationTypeKey: "conference",
    salesInitiative: "tech_conferences",
    opportunityTypeKey: "annual_conference",
    forceManualQueue: true,
    runPipeline: false,
    manualEventName: "ASU+GSV Summit 2027",
    manualQueueTitle: "ASU+GSV Summit 2027 — San Diego (Apr 4–7) participatory anthem",
    manualQueueDescription:
      "Premier education/skills innovation summit (7,000+). Pitch a participatory anthem for the learning economy.",
    eventDateEstimate: "2027-04-04",
    eventDateConfidence: "confirmed",
    contacts: [
      {
        fullName: "Phil Walker",
        email: "pwalker@gsv.com",
        roleTitle: "Senior Vice President, Global Event Operations",
        roleCategory: "events",
        emailVerificationStatus: "verified_deliverable",
        roleDescription: "SVP Global Event Operations — primary owner of ASU+GSV summit delivery.",
      },
      {
        fullName: "Julia Hieser",
        email: "jhieser@gsv.com",
        roleTitle: "Senior Vice President, Community & Program",
        roleCategory: "events",
        emailVerificationStatus: "verified_deliverable",
        roleDescription: "SVP Community & Program — owns summit programming and community experience.",
      },
      {
        fullName: "Kelsey Lawson",
        email: "klawson@gsv.com",
        roleTitle: "Event Manager",
        roleCategory: "events",
        emailVerificationStatus: "verified_deliverable",
        roleDescription: "Event manager on the GSV Summit team — day-to-day production doorway.",
      },
    ],
  },
  {
    name: "Transform 2027",
    websiteUrl: "https://www.transform.us/conference/",
    locationCity: "Las Vegas",
    locationRegion: "NV",
    locationCountry: "US",
    organizationTypeKey: "conference",
    salesInitiative: "tech_conferences",
    opportunityTypeKey: "annual_conference",
    forceManualQueue: true,
    runPipeline: false,
    manualEventName: "Transform 2027",
    manualQueueTitle: "Transform 2027 — Las Vegas (Apr 12–14) participatory anthem",
    manualQueueDescription:
      "Transform conference (4,500 advertised). Pitch a participatory anthem for the Transform community.",
    eventDateEstimate: "2027-04-12",
    eventDateConfidence: "confirmed",
    contacts: [
      {
        fullName: "Roxanne Hodges",
        email: "roxanne@transform.us",
        roleTitle: "Event Operations Manager",
        roleCategory: "events",
        emailVerificationStatus: "verified_deliverable",
        roleDescription: "Event operations manager — owns on-site conference production.",
      },
      {
        fullName: "Jason Heathcote",
        email: "jason@transform.us",
        roleTitle: "Head of Community",
        roleCategory: "events",
        emailVerificationStatus: "verified_deliverable",
        roleDescription: "Head of community — cares how the room feels and what people create together.",
      },
      {
        fullName: "Enrique Pulgar",
        email: "enrique@transform.us",
        roleTitle: "Global Community Director",
        roleCategory: "events",
        emailVerificationStatus: "verified_deliverable",
        roleDescription: "Global community director — senior doorway for signature community experiences.",
      },
    ],
  },
  {
    name: "Human Potential Summit",
    websiteUrl: "https://www.humanpotentialnetwork.co/summit-faq",
    locationCity: "Park City",
    locationRegion: "UT",
    locationCountry: "US",
    organizationTypeKey: "conference",
    salesInitiative: "conferences_associations",
    opportunityTypeKey: "annual_conference",
    forceManualQueue: true,
    runPipeline: false,
    manualEventName: "Human Potential Summit 2026",
    manualQueueTitle: "Human Potential Summit — Park City (Oct 21–23) participatory anthem",
    manualQueueDescription:
      "Human Potential Network summit (~300). Pitch a participatory anthem for workforce/education leaders.",
    eventDateEstimate: "2026-10-21",
    eventDateConfidence: "confirmed",
    contacts: [
      {
        fullName: "George Vinton",
        email: "george@commongroup.org",
        roleTitle: "CEO & Founder, Common Group (Summit producer)",
        roleCategory: "executive",
        emailVerificationStatus: "verified_deliverable",
        roleDescription: "Common Group CEO — publicly owns Human Potential Summit partnership and can green-light programming.",
      },
      {
        fullName: "Human Potential Summit",
        email: "connect@humanpotentialsummit.co",
        roleTitle: "Summit organizer inbox",
        roleCategory: "events",
        emailVerificationStatus: "verified_deliverable",
        roleDescription: "Published summit inbox — primary route for programming and partnership asks.",
      },
      {
        fullName: "Common Group Info",
        email: "info@commongroup.org",
        roleTitle: "Common Group general inbox (summit design partner)",
        roleCategory: "events",
        emailVerificationStatus: "verified_deliverable",
        roleDescription: "Common Group inbox — route to Jennifer Stredler (MD leading summit design; no verified personal email).",
      },
    ],
  },
  {
    name: "Responsive Conference",
    websiteUrl: "https://www.responsiveconference.com/",
    locationCity: null,
    locationRegion: null,
    locationCountry: "US",
    organizationTypeKey: "conference",
    salesInitiative: "conferences_associations",
    opportunityTypeKey: "annual_conference",
    forceManualQueue: true,
    runPipeline: false,
    manualEventName: "Responsive Conference 2027",
    manualQueueTitle: "Responsive Conference 2027 — participatory anthem (~250)",
    manualQueueDescription:
      "Future-of-work / org-design conference. Pitch a participatory anthem fitting the unconference ethos.",
    eventDateEstimate: "2027-09-22",
    eventDateConfidence: "confirmed",
    contacts: [
      {
        fullName: "Robin P Zander",
        email: "robin@zandermedia.com",
        roleTitle: "Executive Director / Founder",
        roleCategory: "executive",
        emailVerificationStatus: "verified_deliverable",
        roleDescription: "Executive director of Responsive Conference — owns programming and partnerships.",
      },
      {
        fullName: "Grace Moen",
        email: "grace@gracemoen.com",
        roleTitle: "Speaker Liaison",
        roleCategory: "events",
        emailVerificationStatus: "verified_deliverable",
        roleDescription: "Published Responsive team speaker liaison — owns speaker and stage-side coordination.",
      },
      {
        fullName: "Responsive Conference",
        email: "hello@responsiveconference.com",
        roleTitle: "Conference team inbox",
        roleCategory: "events",
        emailVerificationStatus: "verified_deliverable",
        roleDescription: "Published Responsive Conference inbox — sponsorship and programming inquiries.",
      },
    ],
  },
  {
    name: "Artifact AI Summit",
    websiteUrl: "https://artifactsummit.com/",
    locationCity: "Alachua",
    locationRegion: "FL",
    locationCountry: "US",
    organizationTypeKey: "conference",
    salesInitiative: "tech_conferences",
    opportunityTypeKey: "annual_conference",
    forceManualQueue: true,
    runPipeline: false,
    manualEventName: "Artifact AI Summit 2027",
    manualQueueTitle: "Artifact AI Summit — Alachua (Feb 12) participatory anthem",
    manualQueueDescription:
      "Human-centered AI summit on a ranch. Pitch a participatory anthem matching the intimate format.",
    eventDateEstimate: "2027-02-12",
    eventDateConfidence: "confirmed",
    contacts: [
      {
        fullName: "Pia Simeoni",
        email: "pia@weareartifact.com",
        roleTitle: "Chief Intelligence Officer / Summit lead",
        roleCategory: "events",
        emailVerificationStatus: "verified_deliverable",
        roleDescription: "CIO credited with planning the 2027 Artifact AI Summit details.",
      },
      {
        fullName: "Jasmine Artifact",
        email: "jasmine@weareartifact.com",
        roleTitle: "Media / Summit contact",
        roleCategory: "marketing",
        emailVerificationStatus: "verified_deliverable",
        roleDescription: "Published Artifact Summit media contact.",
      },
      {
        fullName: "Boaz Artifact",
        email: "boaz@weareartifact.com",
        roleTitle: "Artifact team",
        roleCategory: "executive",
        emailVerificationStatus: "verified_deliverable",
        roleDescription: "Artifact team contact on the summit organizer domain.",
      },
    ],
  },
  {
    name: "Human Capability Initiative",
    websiteUrl: "https://www.humancapabilityinitiative.org/en",
    locationCity: "Riyadh",
    locationRegion: null,
    locationCountry: "SA",
    organizationTypeKey: "conference",
    salesInitiative: "conferences_associations",
    opportunityTypeKey: "annual_conference",
    forceManualQueue: true,
    runPipeline: false,
    manualEventName: "Human Capability Initiative 2027",
    manualQueueTitle: "HCI 2027 — Riyadh (Apr 12–13) participatory anthem",
    manualQueueDescription:
      "Saudi Human Capability Development Program global conference. Pitch only via official program channels.",
    eventDateEstimate: "2027-04-12",
    eventDateConfidence: "confirmed",
    contacts: [
      {
        fullName: "HCI Program",
        email: "program@humancapabilityinitiative.org",
        roleTitle: "Speaking and partnership inquiries",
        roleCategory: "events",
        emailVerificationStatus: "verified_deliverable",
        roleDescription: "Published program inbox for speaking and partnership — primary HCI doorway.",
      },
      {
        fullName: "HCI Media",
        email: "media@humancapabilityinitiative.org",
        roleTitle: "Media inquiries",
        roleCategory: "marketing",
        emailVerificationStatus: "verified_deliverable",
        roleDescription: "Published media inbox — route story/experience proposals here if program is silent.",
      },
      {
        fullName: "HCI Info",
        email: "info@humancapabilityinitiative.org",
        roleTitle: "General conference inquiries",
        roleCategory: "events",
        emailVerificationStatus: "verified_deliverable",
        roleDescription: "Published general inbox — fallback when named HCDP directors have no public emails.",
      },
    ],
  },
  {
    name: "Collaborative — GoFundMe Pro",
    websiteUrl: "https://collaborative.gofundme.com/",
    locationCity: "Chicago",
    locationRegion: "IL",
    locationCountry: "US",
    organizationTypeKey: "corporation",
    salesInitiative: "fundraising_galas",
    opportunityTypeKey: "annual_conference",
    forceManualQueue: true,
    runPipeline: false,
    manualEventName: "Collaborative 2027",
    manualQueueTitle: "Collaborative 2027 (GoFundMe Pro) — Chicago (May 5–6) participatory anthem",
    manualQueueDescription:
      "GoFundMe Pro nonprofit fundraiser conference. Pitch a participatory anthem for the Collaborative community.",
    eventDateEstimate: "2027-05-05",
    eventDateConfidence: "confirmed",
    contacts: [
      {
        fullName: "Kayla Robinson",
        email: "krobinson@gofundme.com",
        roleTitle: "Marketing Events Manager",
        roleCategory: "events",
        emailVerificationStatus: "verified_deliverable",
        roleDescription: "Marketing events manager — owns GoFundMe event production including Collaborative.",
      },
      {
        fullName: "Brianne Vertrees",
        email: "bvertrees@gofundme.com",
        roleTitle: "Director of Community Engagement",
        roleCategory: "events",
        emailVerificationStatus: "verified_deliverable",
        roleDescription: "Director of community engagement — cares how the nonprofit community experiences Collaborative.",
      },
      {
        fullName: "Natasha Harris",
        email: "nharris@gofundme.com",
        roleTitle: "Marketing Content Manager",
        roleCategory: "marketing",
        emailVerificationStatus: "verified_deliverable",
        roleDescription: "Marketing content — doorway for how a live moment becomes the conference story.",
      },
    ],
  },
  {
    name: "Tom Tom Festival",
    websiteUrl: "https://www.tomtomfoundation.org/post/2027-conference-creator",
    locationCity: "Charlottesville",
    locationRegion: "VA",
    locationCountry: "US",
    organizationTypeKey: "festival",
    salesInitiative: "arts_culture",
    opportunityTypeKey: "annual_conference",
    forceManualQueue: true,
    runPipeline: false,
    manualEventName: "Tom Tom Festival 2027",
    manualQueueTitle: "Tom Tom Festival 2027 — Charlottesville (Apr 21–25) participatory anthem",
    manualQueueDescription:
      "Tom Tom Foundation ideas/creator festival. Pitch a participatory anthem for the Charlottesville convening.",
    eventDateEstimate: "2027-04-21",
    eventDateConfidence: "confirmed",
    contacts: [
      {
        fullName: "Paul Beyer",
        email: "paul@tomtomfoundation.org",
        roleTitle: "Executive Director",
        roleCategory: "executive",
        emailVerificationStatus: "verified_deliverable",
        roleDescription: "ED — owns Tom Tom Festival direction and can green-light signature moments.",
      },
      {
        fullName: "Angelica Merritt",
        email: "angelica@tomtomfoundation.org",
        roleTitle: "Production Manager",
        roleCategory: "events",
        emailVerificationStatus: "verified_deliverable",
        roleDescription: "Production manager — primary owner of festival production logistics.",
      },
      {
        fullName: "Erin Ryan",
        email: "erin@tomtomfoundation.org",
        roleTitle: "Director of Operations",
        roleCategory: "operations",
        emailVerificationStatus: "verified_deliverable",
        roleDescription: "Director of operations — cross-team router for festival programming asks.",
      },
    ],
  },
  {
    name: "Keep America Beautiful Summit",
    websiteUrl: "https://kab.org/summit/",
    locationCity: "Savannah",
    locationRegion: "GA",
    locationCountry: "US",
    organizationTypeKey: "nonprofit",
    salesInitiative: "conferences_associations",
    opportunityTypeKey: "annual_conference",
    forceManualQueue: true,
    runPipeline: false,
    manualEventName: "Keep America Beautiful Summit 2027",
    manualQueueTitle: "KAB Summit 2027 — Savannah (Feb 14–17) participatory anthem",
    manualQueueDescription:
      "Keep America Beautiful national summit. Pitch a participatory anthem for community/beautification leaders.",
    eventDateEstimate: "2027-02-14",
    eventDateConfidence: "confirmed",
    contacts: [
      {
        fullName: "Losida Garcia",
        email: "lgarcia@kab.org",
        roleTitle: "Program Director",
        roleCategory: "events",
        emailVerificationStatus: "verified_deliverable",
        roleDescription: "Program director — owns summit and program design.",
      },
      {
        fullName: "Allison Hannel",
        email: "ahannel@kab.org",
        roleTitle: "Chief Marketing Officer",
        roleCategory: "marketing",
        emailVerificationStatus: "verified_deliverable",
        roleDescription: "CMO — owns summit narrative and attendee experience story.",
      },
      {
        fullName: "Becky Lyons",
        email: "blyons@kab.org",
        roleTitle: "Chief Operating Officer",
        roleCategory: "executive",
        emailVerificationStatus: "verified_deliverable",
        roleDescription: "COO — can green-light or route a high-visibility summit experience.",
      },
    ],
  },
  {
    name: "Global Corporate Venturing & Innovation Summit",
    websiteUrl: "https://www.gcvisummit.com/",
    locationCity: "Monterey",
    locationRegion: "CA",
    locationCountry: "US",
    organizationTypeKey: "conference",
    salesInitiative: "tech_conferences",
    opportunityTypeKey: "annual_conference",
    forceManualQueue: true,
    runPipeline: false,
    manualEventName: "GCVI Summit 2027",
    manualQueueTitle: "GCVI Summit 2027 — Monterey (Feb 23–25) participatory anthem",
    manualQueueDescription:
      "Global Corporate Venturing & Innovation Summit (800+). Pitch a participatory anthem for corp venturing leaders.",
    eventDateEstimate: "2027-02-23",
    eventDateConfidence: "confirmed",
    contacts: [
      {
        fullName: "Melanie Serge",
        email: "mserge@globalventuring.com",
        roleTitle: "Senior Director of Events",
        roleCategory: "events",
        emailVerificationStatus: "verified_deliverable",
        roleDescription: "Senior director of events at Global Venturing — primary owner of GCVI Summit production.",
      },
      {
        fullName: "Emily Rudd",
        email: "erudd@globalventuring.com",
        roleTitle: "Customer Engagement Manager (GCVI)",
        roleCategory: "events",
        emailVerificationStatus: "verified_deliverable",
        roleDescription: "Published GCVI networking/tickets contact — day-to-day summit engagement doorway.",
      },
      {
        fullName: "Charlie Hayward",
        email: "chayward@globalventuring.com",
        roleTitle: "Deputy Managing Director, GCV",
        roleCategory: "executive",
        emailVerificationStatus: "verified_deliverable",
        roleDescription: "Deputy MD — appears on GCVI agenda as summit host; can green-light signature programming.",
      },
    ],
  },
  {
    name: "Rio2C",
    websiteUrl: "https://www.rio2c.com/en/",
    locationCity: "Rio de Janeiro",
    locationRegion: null,
    locationCountry: "BR",
    organizationTypeKey: "festival",
    salesInitiative: "entertainment_media",
    opportunityTypeKey: "annual_conference",
    forceManualQueue: true,
    runPipeline: false,
    manualEventName: "Rio2C 2027",
    manualQueueTitle: "Rio2C 2027 — Rio (Apr 12–17) participatory anthem",
    manualQueueDescription:
      "Rio2C creativity/innovation festival (55,000 in 2026). Pitch a participatory anthem for a signature stage.",
    eventDateEstimate: "2027-04-12",
    eventDateConfidence: "confirmed",
    contacts: [
      {
        fullName: "Cris Barreto",
        email: "cris@rio2c.com",
        roleTitle: "Director of Programming and New Business",
        roleCategory: "events",
        emailVerificationStatus: "verified_deliverable",
        roleDescription: "Director of programming — primary buyer for stage and format innovations.",
      },
      {
        fullName: "Daniela Zanuncio",
        email: "daniela@rio2c.com",
        roleTitle: "Executive Producer",
        roleCategory: "events",
        emailVerificationStatus: "verified_deliverable",
        roleDescription: "Executive producer — owns live production of Rio2C experiences.",
      },
      {
        fullName: "Barbara Libanio",
        email: "barbara@rio2c.com",
        roleTitle: "Curator",
        roleCategory: "events",
        emailVerificationStatus: "verified_deliverable",
        roleDescription: "Curator — shapes content and the creative arc of the festival.",
      },
    ],
  },
  {
    name: "X5 Convergence",
    websiteUrl: "https://x5convergence.com/",
    locationCity: null,
    locationRegion: "UT",
    locationCountry: "US",
    organizationTypeKey: "festival",
    salesInitiative: "tech_conferences",
    opportunityTypeKey: "annual_conference",
    forceManualQueue: true,
    runPipeline: false,
    manualEventName: "X5 Convergence 2027",
    manualQueueTitle: "X5 Convergence 2027 — Utah (Sep 16–27) participatory anthem",
    manualQueueDescription:
      "Utah culture/tech/capital convergence (75,000+ projected). Pitch a participatory anthem for a signature activation.",
    eventDateEstimate: "2027-09-16",
    eventDateConfidence: "confirmed",
    contacts: [
      {
        fullName: "Kevin OKeefe",
        email: "kevin@x5fest.com",
        roleTitle: "Co-CEO / Platform Operations (Peaks Art Fairs)",
        roleCategory: "events",
        emailVerificationStatus: "verified_deliverable",
        roleDescription: "Co-CEO for platform operations — organizing force behind X5 cultural activations.",
      },
      {
        fullName: "David Steenhoek",
        email: "david@x5fest.com",
        roleTitle: "Vice Chair & Chief Creative Officer",
        roleCategory: "events",
        emailVerificationStatus: "verified_deliverable",
        roleDescription: "Chief creative officer — owns creative programming for X5 convergence.",
      },
      {
        fullName: "Briana Dolan",
        email: "briana@peaksartfairs.com",
        roleTitle: "Executive, Peaks Art Fairs",
        roleCategory: "events",
        emailVerificationStatus: "verified_deliverable",
        roleDescription: "Peaks Art Fairs executive — partner org producing X5 art-show activations.",
      },
    ],
  },
  {
    name: "Creative Bureaucracy Festival",
    websiteUrl: "https://creativebureaucracy.org/",
    locationCity: "Berlin",
    locationRegion: null,
    locationCountry: "DE",
    organizationTypeKey: "festival",
    salesInitiative: "arts_culture",
    opportunityTypeKey: "annual_conference",
    forceManualQueue: true,
    runPipeline: false,
    manualEventName: "Creative Bureaucracy Festival 2027",
    manualQueueTitle: "Creative Bureaucracy Festival — Berlin (Jun 2–3) participatory anthem",
    manualQueueDescription:
      "Public-sector innovation festival (Falling Walls). Pitch a participatory anthem for changemakers in government.",
    eventDateEstimate: "2027-06-02",
    eventDateConfidence: "confirmed",
    contacts: [
      {
        fullName: "Bernd Fesel",
        email: "bernd.fesel@creativebureaucracy.org",
        roleTitle: "Festival Director",
        roleCategory: "events",
        emailVerificationStatus: "verified_deliverable",
        roleDescription: "Festival director — primary owner of Creative Bureaucracy Festival programming.",
      },
      {
        fullName: "Laura Walther",
        email: "laura.walther@creativebureaucracy.org",
        roleTitle: "Communications Project Manager",
        roleCategory: "marketing",
        emailVerificationStatus: "verified_deliverable",
        roleDescription: "Communications PM — doorway for story and stage partnerships.",
      },
      {
        fullName: "Juliane Bahl",
        email: "juliane.bahl@creativebureaucracy.org",
        roleTitle: "Project Management",
        roleCategory: "events",
        emailVerificationStatus: "verified_deliverable",
        roleDescription: "Project management on the festival team — production collaborator.",
      },
    ],
  },
  {
    name: "SXSW Innovation",
    websiteUrl: "https://sxsw.com/innovation-conference/",
    locationCity: "Austin",
    locationRegion: "TX",
    locationCountry: "US",
    organizationTypeKey: "conference",
    salesInitiative: "tech_conferences",
    opportunityTypeKey: "annual_conference",
    forceManualQueue: true,
    runPipeline: false,
    manualEventName: "SXSW Innovation 2027",
    manualQueueTitle: "SXSW Innovation 2027 — Austin (Mar 15–20) participatory anthem",
    manualQueueDescription:
      "SXSW Innovation Conference. Pitch a participatory anthem to the Innovation Conference director.",
    eventDateEstimate: "2027-03-15",
    eventDateConfidence: "confirmed",
    contacts: [
      {
        fullName: "Katie Perera",
        email: "katie@sxsw.com",
        roleTitle: "Director of Innovation Conference",
        roleCategory: "events",
        emailVerificationStatus: "verified_deliverable",
        roleDescription: "Director of Innovation Conference — the direct owner of this track.",
      },
      {
        fullName: "Greg Rosenbaum",
        email: "greg@sxsw.com",
        roleTitle: "Senior Vice President of Programming",
        roleCategory: "events",
        emailVerificationStatus: "verified_deliverable",
        roleDescription: "SVP of programming — senior doorway across SXSW conference programming.",
      },
      {
        fullName: "Stacie Cline",
        email: "cline@sxsw.com",
        roleTitle: "Festival Manager",
        roleCategory: "events",
        emailVerificationStatus: "verified_deliverable",
        roleDescription: "Festival manager — production doorway for SXSW live experiences.",
      },
    ],
  },
];
