/**
 * Day-1+ national / hall-scale targets for keynote-tier Crowdsource Choir outreach.
 * Attendance / budget proxies: national association annuals & major industry conferences
 * that routinely book convention centers (2,000+ attendees, $250k+ event budgets).
 */

export type NationalKeynoteTarget = {
  name: string;
  websiteUrl: string;
  organizationTypeKey: "association" | "conference" | "nonprofit" | "corporation";
  salesInitiative: "conferences_associations" | "fundraising_galas" | "arts_culture" | "tech_conferences";
  notes: string;
};

export const NATIONAL_KEYNOTE_TARGETS: NationalKeynoteTarget[] = [
  {
    name: "American Library Association",
    websiteUrl: "https://www.ala.org",
    organizationTypeKey: "association",
    salesInitiative: "conferences_associations",
    notes: "ALA Annual — major convention-center national",
  },
  {
    name: "National Education Association",
    websiteUrl: "https://www.nea.org",
    organizationTypeKey: "association",
    salesInitiative: "conferences_associations",
    notes: "RA / national educators gathering",
  },
  {
    name: "SHRM",
    websiteUrl: "https://www.shrm.org",
    organizationTypeKey: "association",
    salesInitiative: "conferences_associations",
    notes: "SHRM Annual Conference — hall-scale HR",
  },
  {
    name: "American Society of Association Executives",
    websiteUrl: "https://www.asaecenter.org",
    organizationTypeKey: "association",
    salesInitiative: "conferences_associations",
    notes: "ASAE Annual — meetings industry buyers",
  },
  {
    name: "PCMA",
    websiteUrl: "https://www.pcma.org",
    organizationTypeKey: "association",
    salesInitiative: "conferences_associations",
    notes: "Convening Leaders — meeting planners",
  },
  {
    name: "International Association of Exhibitions and Events",
    websiteUrl: "https://www.iaee.com",
    organizationTypeKey: "association",
    salesInitiative: "conferences_associations",
    notes: "Expo! Expo! — exhibition industry",
  },
  {
    name: "MPI",
    websiteUrl: "https://www.mpi.org",
    organizationTypeKey: "association",
    salesInitiative: "conferences_associations",
    notes: "World Education Congress — planners",
  },
  {
    name: "American Hospital Association",
    websiteUrl: "https://www.aha.org",
    organizationTypeKey: "association",
    salesInitiative: "conferences_associations",
    notes: "AHA Leadership Summit / Annual — national only",
  },
  {
    name: "Healthcare Financial Management Association",
    websiteUrl: "https://www.hfma.org",
    organizationTypeKey: "association",
    salesInitiative: "conferences_associations",
    notes: "HFMA Annual — large healthcare finance",
  },
  {
    name: "American Nurses Association",
    websiteUrl: "https://www.nursingworld.org",
    organizationTypeKey: "association",
    salesInitiative: "conferences_associations",
    notes: "ANA Membership Assembly / national events",
  },
  {
    name: "Radiological Society of North America",
    websiteUrl: "https://www.rsna.org",
    organizationTypeKey: "association",
    salesInitiative: "conferences_associations",
    notes: "RSNA Annual Meeting — massive medical",
  },
  {
    name: "American College of Cardiology",
    websiteUrl: "https://www.acc.org",
    organizationTypeKey: "association",
    salesInitiative: "conferences_associations",
    notes: "ACC Annual Scientific Session",
  },
  {
    name: "American Academy of Ophthalmology",
    websiteUrl: "https://www.aao.org",
    organizationTypeKey: "association",
    salesInitiative: "conferences_associations",
    notes: "AAO Annual Meeting",
  },
  {
    name: "National Association of Realtors",
    websiteUrl: "https://www.nar.realtor",
    organizationTypeKey: "association",
    salesInitiative: "conferences_associations",
    notes: "NAR NXT — large national realtor gathering",
  },
  {
    name: "National Retail Federation",
    websiteUrl: "https://nrf.com",
    organizationTypeKey: "association",
    salesInitiative: "conferences_associations",
    notes: "Retail's Big Show — NYC hall-scale",
  },
  {
    name: "International Franchise Association",
    websiteUrl: "https://www.franchise.org",
    organizationTypeKey: "association",
    salesInitiative: "conferences_associations",
    notes: "IFA Annual Convention",
  },
  {
    name: "National Restaurant Association",
    websiteUrl: "https://restaurant.org",
    organizationTypeKey: "association",
    salesInitiative: "conferences_associations",
    notes: "NRA Show — enormous trade + programming",
  },
  {
    name: "American Bankers Association",
    websiteUrl: "https://www.aba.com",
    organizationTypeKey: "association",
    salesInitiative: "conferences_associations",
    notes: "ABA Annual Convention",
  },
  {
    name: "Credit Union National Association",
    websiteUrl: "https://www.cuna.org",
    organizationTypeKey: "association",
    salesInitiative: "conferences_associations",
    notes: "CUNA Governmental Affairs / national meetings",
  },
  {
    name: "National Association of Broadcasters",
    websiteUrl: "https://www.nab.org",
    organizationTypeKey: "association",
    salesInitiative: "conferences_associations",
    notes: "NAB Show — huge media/tech",
  },
  {
    name: "National Association of Music Merchants",
    websiteUrl: "https://www.namm.org",
    organizationTypeKey: "association",
    salesInitiative: "arts_culture",
    notes: "NAMM Show — music industry (hall-scale)",
  },
  {
    name: "National Art Education Association",
    websiteUrl: "https://www.arteducators.org",
    organizationTypeKey: "association",
    salesInitiative: "arts_culture",
    notes: "NAEA National Convention",
  },
  {
    name: "Americans for the Arts",
    websiteUrl: "https://www.americansforthearts.org",
    organizationTypeKey: "nonprofit",
    salesInitiative: "arts_culture",
    notes: "Annual Convention — arts leaders",
  },
  {
    name: "League of American Orchestras",
    websiteUrl: "https://americanorchestras.org",
    organizationTypeKey: "association",
    salesInitiative: "arts_culture",
    notes: "National Conference — orchestra leaders",
  },
  {
    name: "Opera America",
    websiteUrl: "https://www.operaamerica.org",
    organizationTypeKey: "association",
    salesInitiative: "arts_culture",
    notes: "Opera Conference — national",
  },
  {
    name: "Theatre Communications Group",
    websiteUrl: "https://www.tcg.org",
    organizationTypeKey: "nonprofit",
    salesInitiative: "arts_culture",
    notes: "TCG National Conference",
  },
  {
    name: "Independent Sector",
    websiteUrl: "https://independentsector.org",
    organizationTypeKey: "nonprofit",
    salesInitiative: "fundraising_galas",
    notes: "Upswell / national nonprofit leaders",
  },
  {
    name: "Council on Foundations",
    websiteUrl: "https://cof.org",
    organizationTypeKey: "nonprofit",
    salesInitiative: "fundraising_galas",
    notes: "COF Annual Conference",
  },
  {
    name: "Association of Fundraising Professionals",
    websiteUrl: "https://afpglobal.org",
    organizationTypeKey: "association",
    salesInitiative: "fundraising_galas",
    notes: "AFP ICON — national fundraising",
  },
  {
    name: "LeadingAge",
    websiteUrl: "https://leadingage.org",
    organizationTypeKey: "association",
    salesInitiative: "conferences_associations",
    notes: "LeadingAge Annual Meeting — large aging services",
  },
  {
    name: "National League of Cities",
    websiteUrl: "https://www.nlc.org",
    organizationTypeKey: "association",
    salesInitiative: "conferences_associations",
    notes: "City Summit — already in funnel; keep national",
  },
  {
    name: "International City/County Management Association",
    websiteUrl: "https://icma.org",
    organizationTypeKey: "association",
    salesInitiative: "conferences_associations",
    notes: "ICMA Annual Conference",
  },
  {
    name: "American Planning Association",
    websiteUrl: "https://www.planning.org",
    organizationTypeKey: "association",
    salesInitiative: "conferences_associations",
    notes: "NPC — National Planning Conference",
  },
  {
    name: "Association for Computing Machinery",
    websiteUrl: "https://www.acm.org",
    organizationTypeKey: "association",
    salesInitiative: "tech_conferences",
    notes: "Large ACM conferences (select flagship)",
  },
  {
    name: "IEEE",
    websiteUrl: "https://www.ieee.org",
    organizationTypeKey: "association",
    salesInitiative: "tech_conferences",
    notes: "Flagship IEEE events — hall-scale",
  },
  {
    name: "Salesforce",
    websiteUrl: "https://www.salesforce.com",
    organizationTypeKey: "corporation",
    salesInitiative: "tech_conferences",
    notes: "Dreamforce — mega keynote stage",
  },
  {
    name: "Adobe",
    websiteUrl: "https://www.adobe.com",
    organizationTypeKey: "corporation",
    salesInitiative: "tech_conferences",
    notes: "Adobe Summit / MAX — large creative",
  },
  {
    name: "National Association of College Stores",
    websiteUrl: "https://www.nacs.org",
    organizationTypeKey: "association",
    salesInitiative: "conferences_associations",
    notes: "CAMEX — national campus retail",
  },
  {
    name: "NACUBO",
    websiteUrl: "https://www.nacubo.org",
    organizationTypeKey: "association",
    salesInitiative: "conferences_associations",
    notes: "NACUBO Annual Meeting — higher-ed business",
  },
  {
    name: "AAC&U",
    websiteUrl: "https://www.aacu.org",
    organizationTypeKey: "association",
    salesInitiative: "conferences_associations",
    notes: "AAC&U Annual Meeting — higher-ed leaders",
  },
];
